### ISSUE TITLE
Feature: mountPoints

### ISSUE THREAD

**Issue by stevie-** [umotif-public/terraform-aws-ecs-fargate#15]
**What is the current behavior?**
There is a way to set up volumes, but in container definition you can not setup mountpoints.

**What is the expected behavior?**
Please add `mountPoints`to container definition to be able to use EFS fe https://docs.aws.amazon.com/AmazonECS/latest/developerguide/efs-volumes.html#specify-efs-config

**Comment by marcincuber** [comment]
Thanks for raising this feature request. I will aim to add this feature to 1.4.0 release this week.

**Comment by marcincuber** [comment]
@stevie- Functionality has been released as part of 1.4.0
