### ISSUE TITLE
Error: InvalidParameterException: The values specified for serviceRegistries do not require a value for 'containerPort'. Remove the value and retry.

### ISSUE THREAD

**Issue by ericduvic** [umotif-public/terraform-aws-ecs-fargate#25]
**What is the current behavior?**
Attempting to set up private DNS service discovery for the fargate service created by this module, I get the error message
`Error: InvalidParameterException: The values specified for serviceRegistries do not require a value for 'containerPort'. Remove the value and retry.` followed by the registry ARN and name.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In my instantiation of the Umotif Fargate module I added shit parameter:
`service_registry_arn = aws_service_discovery_service.service.arn` which references a Service Discovery Service resource.

**What is the expected behavior?**
Everything provisions successfully and the Fargate service updates the Service Discovery service as required.

**Software versions?**
- Terraform v0.13.5
- terraform-aws-ecs-fargate v4.0.3

**Comment by marcincuber** [comment]
@ericduvic 
Hi, I think this is something that Terraform supports but AWS's api doesn't like when you provide containerPort value. Looking at the docs it will default to whatever port task is using. 

Could you please point you module at `fix/registries` branch of this repo and see whether that fixes the problem? It would be great to fix asap

**Comment by ericduvic** [comment]
@marcincuber This seems to have fixed the issue. Thanks so much for your swift reply!

**Comment by marcincuber** [comment]
@ericduvic thanks for reporting and the fix is now released in `5.0.1` version

**Comment by velinbudinov** [comment]
@marcincuber actually if you're going to use service discovery and create a DNS record of type `SRV`, you will need `container_port` parameter, which you've removed with https://github.com/umotif-public/terraform-aws-ecs-fargate/pull/26

<img width="780" alt="image" src="https://github.com/umotif-public/terraform-aws-ecs-fargate/assets/29709127/52bc1307-8512-4a91-8dbb-e066b3998d1e">
