### ISSUE TITLE
Secrets support

### ISSUE THREAD

**Issue by ericduvic** [umotif-public/terraform-aws-ecs-fargate#27]
**What is the current behavior?**
There's no variable for declaring secrets in the task definition

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I guess this is more of a feature request?

**What is the expected behavior?**
A `secrets` variable is available that replicates functionality in the task definition parameter as provided by https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

**Software versions?**
Latest versions of terraform and umotif-public/terraform-aws-ecs-fargate

**Comment by ericduvic** [comment]
I've proposed a fix in PR #28

**Comment by ericduvic** [comment]
Merged in, I guess the only thing left is to update the docs

**Comment by marcincuber** [comment]
@ericduvic docs updated and everything is released as part of `5.1.0`
