### ISSUE TITLE
Feature Request: Allow specifying static security group

### ISSUE THREAD

**Issue by Lusitaniae** [umotif-public/terraform-aws-ecs-fargate#32]
I want to use this module to deploy dev environments. 

All these connect to a single database, would make things easy, if there's one database SG and one web server SG shared by all ECS services/

**Comment by Ohid25** [comment]
The way this module works and is intended to work is to only focus on anything related to ECS Fargate. There is a security group that is created by default for the service. 

Specifying static security groups for this module in question, after having thought about it, can be done in these ways based on what we do here at our organisation.

1. Create a (DB or Web Server) security group external to the module.
2. Add security rules external to the module to specify additional rules for interactability with ECS.

Would this suffice for your use case scenario? The scenario we're trying to avoid is adding too much to this module where it becomes a 'one-stop shop', whereby that's not the purpose of this module.

**Comment by Lusitaniae** [comment]
Understand :)

I'm not actively working with Terraform and I'm still learning about using modules and organizing my code the best way.
