### ISSUE TITLE
Error upgrading to v6.x

### ISSUE THREAD

**Issue by lleger** [umotif-public/terraform-aws-ecs-fargate#39]
**What is the current behavior?**
I followed the [instructions](https://github.com/umotif-public/terraform-aws-ecs-fargate/releases/tag/6.0.0) in the release notes for v6.0.0 to upgrade from 5.1.0 → 6.2.0 and ran into an issue. See below:

```
│ Error: Invalid index
│
│   on .terraform/modules/fargate/fargate/main.tf line 156, in resource "aws_lb_listener" "alb_listener":
│  156:     target_group_arn = module.fargate.target_group_arn[0]
│     ├────────────────
│     │ module.fargate.target_group_arn is empty tuple
│
│ The given key does not identify an element in this collection value.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Removed `lb_arn`
- Updated `target_group_arn = module.fargate.target_group_arn[0]`

Terraform reported this as if it was a static failure, so I wasn't really able to debug it much further.

**What is the expected behavior?**
Expected following the upgrade guide would succeed.

**Software versions?**
```console
$ terraform -v
Terraform v0.15.5
on darwin_arm64
```

**Comment by Ohid25** [comment]
Hi @lleger, 

I just retested the upgrade guide. Have you have defined `target_groups` to be something similar to the following:

```
  target_groups = [
    {
      target_group_name = "tg-example"
      container_port    = 80
    }
  ]
```

**Comment by lleger** [comment]
Fairly certain I did, but I had to revert that code. I'll try again soon and let you know.

**Comment by Ohid25** [comment]
When you get a chance to test, you can reopen this issue. Right now, I'll be closing this.
