### ISSUE TITLE
Success codes support

### ISSUE THREAD

**Issue by edobrb** [umotif-public/terraform-aws-ecs-fargate#44]
Is it possible to add the field "success codes" in the health check map? It can be found under advanced settings in the AWS console:
<img width="799" alt="Screenshot 2021-09-06 at 13 56 27" src="https://user-images.githubusercontent.com/50401517/132214426-cf5a0404-8ef3-40ed-9fba-1814ca34fdca.png">

**Comment by Ohid25** [comment]
The equivalent of success codes is [matcher](https://github.com/umotif-public/terraform-aws-ecs-fargate/blob/master/main.tf#L117). Can be confirmed here in the [terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#health_check) too.

**Comment by edobrb** [comment]
You're right, thanks.
