### ISSUE TITLE
blue/green deployments

### ISSUE THREAD

**Issue by dikkeduif** [umotif-public/terraform-aws-ecs-fargate#51]
**What is the current behavior?**
When you add multiple target groups to the module, it also adds these target groups to the load_balancer block in `aws_ecs_server` under the `dynamic "load_balancer"` section. When you want to do a blue/green deployments via CodeDeploy, only one target group should be assigned to the ecs service at any given time. CodeDeploy is swapping these target groups out during the deployment.

What happens now is that the ecs service has multiple target groups assigned, each task's private IP address is added to each target group. When the codedeploy deployment happens, it gets stuck during the install phase, since it can't register the new replacement task in either target group. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
/

**What is the expected behavior?**
Although this may be out of scope for this module and not the intended usage, it would maybe be nice to mention this behavior somewhere in the documentation.

My current workaround is:
- Let the module only create one target group, for you blue deployments
- Outside the module create another target group resource for green deployments, and attach it to a different listener with a different port than your main listener, such as 8080
- In your codedeploy you can now pass both listeners (production listener for example on port 80 and test listener on 8080) and both target groups (blue and green target groups)

The problem will be that after the deployment has gone through, the target groups will have been switched out (codedeploy is doing this), so your infra state will not match your terraform any longer.

When you do a terraform apply after the first deployment, it will want to revert those changes. The module does not provide lifecycle ignore_changes on the `load_balancer` block, and so applying those changes will possibly break the load balancer routing to your ecs service.

The only workaround I've found for that is to clone the repo and to add lifecycle block with ignore_changes on `load_balancer` in the `aws_ecs_server` resource.

**Software versions?**
6.4.1

**Comment by Ohid25** [comment]
Thank you for raising this issue - you can try raising a pull request with your forked repo to add in the lifecycle block and we can have a review of it.
