### ISSUE TITLE
Add support for sidecar containers

### ISSUE THREAD

**Issue by marco-lancini** [umotif-public/terraform-aws-ecs-fargate#68]
**What is the current behavior?**

Currently, this Terraform module only supports one single container to be added to the `container_definitions`
https://github.com/umotif-public/terraform-aws-ecs-fargate/blob/6.7.0/main.tf#L184

**What is the expected behavior?**

It would be useful being able to specify sidecars.

Some references:

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_task_definition.html#basic-example
* https://aws.amazon.com/blogs/compute/nginx-reverse-proxy-sidecar-container-on-amazon-ecs/

**Comment by Ohid25** [comment]
This should now be possible with the introduction of externally supplied container definition in the latest [7.0.0](https://github.com/umotif-public/terraform-aws-ecs-fargate/releases/tag/7.0.0) release!
