### ISSUE TITLE
Make "aws_security_group_rule" "egress_service" rule configurable 

### ISSUE THREAD

**Issue by pabloandres13** [umotif-public/terraform-aws-ecs-fargate#70]
Hello,

Currently we would like to restrict the outgoing traffic for our fargate service. After looking at the source code in "https://github.com/umotif-public/terraform-aws-ecs-fargate/blob/master/main.tf" I just found out that there is a default security rule created which allow all outgoing traffic.
This represent an issue for us, since our security guidelines force us to limit outgoing traffic only to what it is necessary.

Would be possible to add an a feature toggle or input variable like 'deny_egress_to_anywhere' which if set to true then no egress rule will be created?

Something like 

`module "ecs-fargate" {
  source  = "umotif-public/ecs-fargate/aws"
  version = "6.5.0"
  vpc_id             = var.vpc_id
  private_subnet_ids = var.private_subnets_ids

  cluster_id = aws_ecs_cluster.cluster.id
 deny_egress_to_anywhere =  true
`

**Comment by Ohid25** [comment]
Thanks for the contribution - this is now released as [6.7.1](https://github.com/umotif-public/terraform-aws-ecs-fargate/releases/tag/6.7.1)!

**Comment by pabloandres13** [comment]
Thank you for merging. :-D
